// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api_cinema_challenge.Data;

#nullable disable

namespace api_cinema_challenge.Data.Migrations
{
    [DbContext(typeof(CinemaContext))]
    [Migration("20240206124238_UpdateScreeningSeeder")]
    partial class UpdateScreeningSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api_cinema_challenge.Application.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("date")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9301),
                            Email = "Elisabeth@email.com",
                            Name = "Elisabeth",
                            Phone = "56122811"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9330),
                            Email = "David@email.com",
                            Name = "David",
                            Phone = "32734109"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9336),
                            Email = "David@email.com",
                            Name = "David",
                            Phone = "51967771"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9341),
                            Email = "Ruben@email.com",
                            Name = "Ruben",
                            Phone = "99968378"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9345),
                            Email = "Frank@email.com",
                            Name = "Frank",
                            Phone = "41371165"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9356),
                            Email = "Frank@email.com",
                            Name = "Frank",
                            Phone = "16530955"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9361),
                            Email = "David@email.com",
                            Name = "David",
                            Phone = "89877089"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9365),
                            Email = "David@email.com",
                            Name = "David",
                            Phone = "34166824"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9370),
                            Email = "Ruben@email.com",
                            Name = "Ruben",
                            Phone = "37350938"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9376),
                            Email = "George@email.com",
                            Name = "George",
                            Phone = "25439371"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9380),
                            Email = "Ruben@email.com",
                            Name = "Ruben",
                            Phone = "82323535"
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Application.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("RuntimeMins")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_mins");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("date")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9496),
                            Description = "A movie about a Policeman that is quite Fast",
                            Rating = 3,
                            RuntimeMins = 122,
                            Title = "The Fast Policeman"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9636),
                            Description = "A movie about a Piper that is quite Seethrough",
                            Rating = 1,
                            RuntimeMins = 89,
                            Title = "The Seethrough Piper"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9643),
                            Description = "A movie about a Piper that is quite Round",
                            Rating = 2,
                            RuntimeMins = 252,
                            Title = "The Round Piper"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9648),
                            Description = "A movie about a Policeman that is quite Purple",
                            Rating = 0,
                            RuntimeMins = 208,
                            Title = "The Purple Policeman"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9652),
                            Description = "A movie about a Phone that is quite Mad",
                            Rating = 0,
                            RuntimeMins = 203,
                            Title = "The Mad Phone"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9658),
                            Description = "A movie about a Computer that is quite Mad",
                            Rating = 1,
                            RuntimeMins = 172,
                            Title = "The Mad Computer"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9662),
                            Description = "A movie about a Policeman that is quite Round",
                            Rating = 0,
                            RuntimeMins = 194,
                            Title = "The Round Policeman"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9667),
                            Description = "A movie about a Computer that is quite Round",
                            Rating = 0,
                            RuntimeMins = 212,
                            Title = "The Round Computer"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9671),
                            Description = "A movie about a Swan that is quite Round",
                            Rating = 3,
                            RuntimeMins = 241,
                            Title = "The Round Swan"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9676),
                            Description = "A movie about a Phone that is quite Round",
                            Rating = 2,
                            RuntimeMins = 83,
                            Title = "The Round Phone"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9681),
                            Description = "A movie about a Computer that is quite Amazing",
                            Rating = 2,
                            RuntimeMins = 222,
                            Title = "The Amazing Computer"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9685),
                            Description = "A movie about a Computer that is quite Seethrough",
                            Rating = 3,
                            RuntimeMins = 185,
                            Title = "The Seethrough Computer"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9690),
                            Description = "A movie about a Computer that is quite Round",
                            Rating = 1,
                            RuntimeMins = 219,
                            Title = "The Round Computer"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9694),
                            Description = "A movie about a Swan that is quite Slow",
                            Rating = 1,
                            RuntimeMins = 224,
                            Title = "The Slow Swan"
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Application.Models.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("date")
                        .HasColumnName("starts_at");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("screenings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 58,
                            MovieId = 8,
                            StartsAt = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 54,
                            MovieId = 9,
                            StartsAt = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 32,
                            MovieId = 1,
                            StartsAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 38,
                            MovieId = 10,
                            StartsAt = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 55,
                            MovieId = 8,
                            StartsAt = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 56,
                            MovieId = 2,
                            StartsAt = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Application.Models.Ticket", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("integer")
                        .HasColumnName("screening_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at");

                    b.Property<int>("NumSeats")
                        .HasColumnType("integer")
                        .HasColumnName("num_seats");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("date")
                        .HasColumnName("updated_at");

                    b.HasKey("CustomerId", "ScreeningId");

                    b.HasIndex("ScreeningId");

                    b.ToTable("tickets");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            ScreeningId = 3,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9829),
                            NumSeats = 4,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CustomerId = 3,
                            ScreeningId = 4,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9833),
                            NumSeats = 2,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CustomerId = 2,
                            ScreeningId = 1,
                            CreatedAt = new DateTime(2024, 2, 6, 13, 42, 37, 769, DateTimeKind.Local).AddTicks(9836),
                            NumSeats = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Application.Models.Screening", b =>
                {
                    b.HasOne("api_cinema_challenge.Application.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("api_cinema_challenge.Application.Models.Ticket", b =>
                {
                    b.HasOne("api_cinema_challenge.Application.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_cinema_challenge.Application.Models.Screening", null)
                        .WithMany()
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
