// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api_cinema_challenge.Data;

#nullable disable

namespace api_cinema_challenge.Migrations
{
    [DbContext(typeof(CinemaContext))]
    [Migration("20240201152949_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api_cinema_challenge.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rating");

                    b.Property<int>("RuntimeMins")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_mins");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 1, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7254),
                            Description = "A short comedy movie",
                            Rating = "Good",
                            RuntimeMins = 77,
                            Title = "The Sweet Potato",
                            UpdatedAt = new DateTime(2024, 2, 1, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7254)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 27, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7256),
                            Description = "A thrilling mystery movie",
                            Rating = "Excellent",
                            RuntimeMins = 120,
                            Title = "Mystery Mansion",
                            UpdatedAt = new DateTime(2024, 1, 29, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7257)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 22, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7259),
                            Description = "A beautiful romantic movie",
                            Rating = "Great",
                            RuntimeMins = 90,
                            Title = "Romantic Sunset",
                            UpdatedAt = new DateTime(2024, 1, 24, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7259)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 17, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7261),
                            Description = "An epic science fiction movie",
                            Rating = "Excellent",
                            RuntimeMins = 150,
                            Title = "Sci-Fi Odyssey",
                            UpdatedAt = new DateTime(2024, 1, 20, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7261)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 12, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7263),
                            Description = "A gripping drama movie",
                            Rating = "Good",
                            RuntimeMins = 110,
                            Title = "Drama Junction",
                            UpdatedAt = new DateTime(2024, 1, 14, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7263)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<string>("ScreenName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("screen_name");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("screenings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 1, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7361),
                            MovieId = 1,
                            ScreenName = "Screen1",
                            StartTime = new DateTime(2024, 2, 1, 16, 29, 49, 563, DateTimeKind.Utc).AddTicks(7360),
                            UpdatedAt = new DateTime(2024, 2, 1, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7362)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 1, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7366),
                            MovieId = 1,
                            ScreenName = "Screen2",
                            StartTime = new DateTime(2024, 2, 1, 18, 29, 49, 563, DateTimeKind.Utc).AddTicks(7365),
                            UpdatedAt = new DateTime(2024, 2, 1, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7366)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 1, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7368),
                            MovieId = 2,
                            ScreenName = "Screen3",
                            StartTime = new DateTime(2024, 2, 1, 19, 29, 49, 563, DateTimeKind.Utc).AddTicks(7367),
                            UpdatedAt = new DateTime(2024, 2, 1, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7368)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 1, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7370),
                            MovieId = 2,
                            ScreenName = "Screen4",
                            StartTime = new DateTime(2024, 2, 1, 16, 29, 49, 563, DateTimeKind.Utc).AddTicks(7369),
                            UpdatedAt = new DateTime(2024, 2, 1, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7370)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 2, 1, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7372),
                            MovieId = 3,
                            ScreenName = "Screen5",
                            StartTime = new DateTime(2024, 2, 1, 20, 29, 49, 563, DateTimeKind.Utc).AddTicks(7371),
                            UpdatedAt = new DateTime(2024, 2, 1, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7372)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 1, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(6987),
                            Email = "joel@email.com",
                            Name = "Joel Joelsson",
                            PhoneNumber = "0700050088",
                            UpdatedAt = new DateTime(2024, 2, 1, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(6989)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 30, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(6991),
                            Email = "alice@email.com",
                            Name = "Alice Johnson",
                            PhoneNumber = "0701122334",
                            UpdatedAt = new DateTime(2024, 1, 30, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(6998)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 27, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7000),
                            Email = "bob@email.com",
                            Name = "Bob Smith",
                            PhoneNumber = "0709876543",
                            UpdatedAt = new DateTime(2024, 1, 29, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7000)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 24, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7001),
                            Email = "emma@email.com",
                            Name = "Emma White",
                            PhoneNumber = "0703344556",
                            UpdatedAt = new DateTime(2024, 1, 26, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7002)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 22, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7003),
                            Email = "david@email.com",
                            Name = "David Brown",
                            PhoneNumber = "0706677889",
                            UpdatedAt = new DateTime(2024, 1, 25, 15, 29, 49, 563, DateTimeKind.Utc).AddTicks(7004)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
