// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api_cinema_challenge.Data;

#nullable disable

namespace api_cinema_challenge.Migrations
{
    [DbContext(typeof(CinemaContext))]
    [Migration("20240212143550_changedForExtension")]
    partial class changedForExtension
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api_cinema_challenge.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(828),
                            Email = "First.Name@email.provider",
                            Name = "First Name",
                            Phone = "+01 012 34 567",
                            UpdatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(830)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(834),
                            Email = "Second.Name@email.provider",
                            Name = "Second Name",
                            Phone = "+01 112 34 567",
                            UpdatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(834)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(837),
                            Email = "Third.Name@email.provider",
                            Name = "Third Name",
                            Phone = "+01 122 34 567",
                            UpdatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(837)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rating");

                    b.Property<int>("RuntimeMins")
                        .HasColumnType("integer")
                        .HasColumnName("rutimeMins");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(879),
                            Description = "description",
                            Rating = "PG-13",
                            RuntimeMins = 124,
                            Title = "title",
                            UpdatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(880)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(884),
                            Description = "Another description",
                            Rating = "PG-14",
                            RuntimeMins = 60,
                            Title = "title1",
                            UpdatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(884)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(887),
                            Description = "Yet another description",
                            Rating = "PG-18",
                            RuntimeMins = 460,
                            Title = "title2",
                            UpdatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(887)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<int>("ScreenNumber")
                        .HasColumnType("integer")
                        .HasColumnName("screenNumber");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startsAt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("screening");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1,
                            CreatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(908),
                            MovieId = 1,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2024, 2, 9, 20, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(909)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1,
                            CreatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(915),
                            MovieId = 2,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2024, 2, 11, 20, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(915)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 1,
                            CreatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(918),
                            MovieId = 3,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2024, 2, 15, 20, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2024, 2, 12, 14, 35, 50, 316, DateTimeKind.Utc).AddTicks(918)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
