// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api_cinema_challenge.Data;

#nullable disable

namespace api_cinema_challenge.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250128084332_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api_cinema_challenge.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.smith@example.com",
                            Name = "Alice Smith",
                            Phone = "123-456-0001",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.johnson@example.com",
                            Name = "Bob Johnson",
                            Phone = "123-456-0002",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "charlie.williams@example.com",
                            Name = "Charlie Williams",
                            Phone = "123-456-0003",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "diana.jones@example.com",
                            Name = "Diana Jones",
                            Phone = "123-456-0004",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eve.brown@example.com",
                            Name = "Eve Brown",
                            Phone = "123-456-0005",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frank.davis@example.com",
                            Name = "Frank Davis",
                            Phone = "123-456-0006",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "grace.miller@example.com",
                            Name = "Grace Miller",
                            Phone = "123-456-0007",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hank.wilson@example.com",
                            Name = "Hank Wilson",
                            Phone = "123-456-0008",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ivy.moore@example.com",
                            Name = "Ivy Moore",
                            Phone = "123-456-0009",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jack.taylor@example.com",
                            Name = "Jack Taylor",
                            Phone = "123-456-0010",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.smith@example.com",
                            Name = "Alice Smith",
                            Phone = "123-456-0011",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.johnson@example.com",
                            Name = "Bob Johnson",
                            Phone = "123-456-0012",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "charlie.williams@example.com",
                            Name = "Charlie Williams",
                            Phone = "123-456-0013",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "diana.jones@example.com",
                            Name = "Diana Jones",
                            Phone = "123-456-0014",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eve.brown@example.com",
                            Name = "Eve Brown",
                            Phone = "123-456-0015",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frank.davis@example.com",
                            Name = "Frank Davis",
                            Phone = "123-456-0016",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "grace.miller@example.com",
                            Name = "Grace Miller",
                            Phone = "123-456-0017",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hank.wilson@example.com",
                            Name = "Hank Wilson",
                            Phone = "123-456-0018",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ivy.moore@example.com",
                            Name = "Ivy Moore",
                            Phone = "123-456-0019",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jack.taylor@example.com",
                            Name = "Jack Taylor",
                            Phone = "123-456-0020",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.smith@example.com",
                            Name = "Alice Smith",
                            Phone = "123-456-0021",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.johnson@example.com",
                            Name = "Bob Johnson",
                            Phone = "123-456-0022",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "charlie.williams@example.com",
                            Name = "Charlie Williams",
                            Phone = "123-456-0023",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "diana.jones@example.com",
                            Name = "Diana Jones",
                            Phone = "123-456-0024",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eve.brown@example.com",
                            Name = "Eve Brown",
                            Phone = "123-456-0025",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frank.davis@example.com",
                            Name = "Frank Davis",
                            Phone = "123-456-0026",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "grace.miller@example.com",
                            Name = "Grace Miller",
                            Phone = "123-456-0027",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hank.wilson@example.com",
                            Name = "Hank Wilson",
                            Phone = "123-456-0028",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ivy.moore@example.com",
                            Name = "Ivy Moore",
                            Phone = "123-456-0029",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jack.taylor@example.com",
                            Name = "Jack Taylor",
                            Phone = "123-456-0030",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.smith@example.com",
                            Name = "Alice Smith",
                            Phone = "123-456-0031",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.johnson@example.com",
                            Name = "Bob Johnson",
                            Phone = "123-456-0032",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "charlie.williams@example.com",
                            Name = "Charlie Williams",
                            Phone = "123-456-0033",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "diana.jones@example.com",
                            Name = "Diana Jones",
                            Phone = "123-456-0034",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eve.brown@example.com",
                            Name = "Eve Brown",
                            Phone = "123-456-0035",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frank.davis@example.com",
                            Name = "Frank Davis",
                            Phone = "123-456-0036",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "grace.miller@example.com",
                            Name = "Grace Miller",
                            Phone = "123-456-0037",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hank.wilson@example.com",
                            Name = "Hank Wilson",
                            Phone = "123-456-0038",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ivy.moore@example.com",
                            Name = "Ivy Moore",
                            Phone = "123-456-0039",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jack.taylor@example.com",
                            Name = "Jack Taylor",
                            Phone = "123-456-0040",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.smith@example.com",
                            Name = "Alice Smith",
                            Phone = "123-456-0041",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.johnson@example.com",
                            Name = "Bob Johnson",
                            Phone = "123-456-0042",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "charlie.williams@example.com",
                            Name = "Charlie Williams",
                            Phone = "123-456-0043",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "diana.jones@example.com",
                            Name = "Diana Jones",
                            Phone = "123-456-0044",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eve.brown@example.com",
                            Name = "Eve Brown",
                            Phone = "123-456-0045",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frank.davis@example.com",
                            Name = "Frank Davis",
                            Phone = "123-456-0046",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "grace.miller@example.com",
                            Name = "Grace Miller",
                            Phone = "123-456-0047",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hank.wilson@example.com",
                            Name = "Hank Wilson",
                            Phone = "123-456-0048",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ivy.moore@example.com",
                            Name = "Ivy Moore",
                            Phone = "123-456-0049",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jack.taylor@example.com",
                            Name = "Jack Taylor",
                            Phone = "123-456-0050",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RuntimeMins")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description for The Great Adventure",
                            Rating = "G",
                            RuntimeMins = 100,
                            Title = "The Great Adventure",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description for Romance in Paris",
                            Rating = "PG",
                            RuntimeMins = 110,
                            Title = "Romance in Paris",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description for Space Odyssey",
                            Rating = "PG-13",
                            RuntimeMins = 120,
                            Title = "Space Odyssey",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description for The Last Stand",
                            Rating = "R",
                            RuntimeMins = 130,
                            Title = "The Last Stand",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description for Comedy Central",
                            Rating = "NC-17",
                            RuntimeMins = 140,
                            Title = "Comedy Central",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description for Mystery Mansion",
                            Rating = "G",
                            RuntimeMins = 150,
                            Title = "Mystery Mansion",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description for Fast Wheels",
                            Rating = "PG",
                            RuntimeMins = 160,
                            Title = "Fast Wheels",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description for Horror Nights",
                            Rating = "PG-13",
                            RuntimeMins = 170,
                            Title = "Horror Nights",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description for Dreams of Tomorrow",
                            Rating = "R",
                            RuntimeMins = 180,
                            Title = "Dreams of Tomorrow",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Description for The Epic Quest",
                            Rating = "NC-17",
                            RuntimeMins = 190,
                            Title = "The Epic Quest",
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("ScreenNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Screenings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 1,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2023, 10, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 2,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2023, 10, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 3,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2023, 10, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 4,
                            ScreenNumber = 5,
                            StartsAt = new DateTime(2023, 10, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 5,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2023, 10, 6, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 6,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2023, 10, 7, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 7,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2023, 10, 8, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 8,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2023, 10, 9, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 9,
                            ScreenNumber = 5,
                            StartsAt = new DateTime(2023, 10, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 10,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2023, 10, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 1,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2023, 10, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 2,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2023, 10, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 3,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2023, 10, 14, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 4,
                            ScreenNumber = 5,
                            StartsAt = new DateTime(2023, 10, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 5,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2023, 10, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 6,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2023, 10, 17, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 7,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2023, 10, 18, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 8,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2023, 10, 19, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 9,
                            ScreenNumber = 5,
                            StartsAt = new DateTime(2023, 10, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 10,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2023, 10, 21, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 1,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2023, 10, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 2,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2023, 10, 23, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 3,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2023, 10, 24, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 4,
                            ScreenNumber = 5,
                            StartsAt = new DateTime(2023, 10, 25, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 5,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2023, 10, 26, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 6,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2023, 10, 27, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 7,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2023, 10, 28, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 8,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2023, 10, 29, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 9,
                            ScreenNumber = 5,
                            StartsAt = new DateTime(2023, 10, 30, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            Capacity = 100,
                            CreatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 10,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2023, 10, 31, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2023, 9, 30, 22, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Screening", b =>
                {
                    b.HasOne("api_cinema_challenge.Models.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Movie", b =>
                {
                    b.Navigation("Screenings");
                });
#pragma warning restore 612, 618
        }
    }
}
