CREATE TABLE Customers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(50) NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Movies (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    rating VARCHAR(50),
    description TEXT,
    runtimeMins INTEGER NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Screenings (
    id SERIAL PRIMARY KEY,
    movieId INTEGER NOT NULL REFERENCES Movies(id) ON DELETE CASCADE,
    screenNumber INTEGER NOT NULL,
    capacity INTEGER NOT NULL,
    startsAt TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Tickets (
    id SERIAL PRIMARY KEY,
    customerId INTEGER NOT NULL REFERENCES Customers(id) ON DELETE CASCADE,
    screeningId INTEGER NOT NULL REFERENCES Screenings(id) ON DELETE CASCADE,
    numSeats INTEGER NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE Screenings
ADD CONSTRAINT fk_movie
FOREIGN KEY (movieId) REFERENCES Movies(id)
ON DELETE CASCADE;

ALTER TABLE Tickets
ADD CONSTRAINT fk_customer
FOREIGN KEY (customerId) REFERENCES Customers(id)
ON DELETE CASCADE;

ALTER TABLE Tickets
ADD CONSTRAINT fk_screening
FOREIGN KEY (screeningId) REFERENCES Screenings(id)
ON DELETE CASCADE;

